name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish on NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Setup Git
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"

      - run: yarn install
      - run: yarn build

      - name: Publish build from ${{ github.ref }}
        run: |
          version=$(echo $TAG | grep -o -E "[0-9.]+")
          git tag -d "v${version}"
          yarn publish --new-version $version ./lib
        env:
          TAG: ${{ github.ref }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
